package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunReportsFunctionsAndMethodsAsJSON verifies the analyzer's machine-readable contract.
//
// Expected: functions and methods expose stable kind, receiver, count, complexity and line metrics.
func TestRunReportsFunctionsAndMethodsAsJSON(t *testing.T) {
	// Given: source containing a function and a method with distinct signatures and branches.
	root := t.TempDir()
	writeGoFixture(t, root, "sample.go",
		"package sample\n\n"+
			"type Store struct{}\n\n"+
			"func Add(left, right int) int {\n"+
			"\treturn left + right\n"+
			"}\n\n"+
			"func (s *Store) Save(ctx any, first, second string, values ...int) (int, error) {\n"+
			"\tif first == \"\" || second == \"\" {\n"+
			"\t\treturn 0, nil\n"+
			"\t}\n"+
			"\treturn len(values), nil\n"+
			"}\n")

	var stdout bytes.Buffer
	var stderr bytes.Buffer

	// When: the analyzer emits its JSON report.
	code := run([]string{"-root", root, "-format", "json"}, &stdout, &stderr)

	// Then: the report preserves symbol identity, counts, complexity and line bounds.
	if code != 0 {
		t.Fatalf("run() code = %d, want 0; stderr=%s", code, stderr.String())
	}

	var report Report
	if err := json.Unmarshal(stdout.Bytes(), &report); err != nil {
		t.Fatalf("decode JSON: %v\n%s", err, stdout.String())
	}
	if len(report.Metrics) != 2 {
		t.Fatalf("metrics count = %d, want 2", len(report.Metrics))
	}

	add := metricNamed(t, report.Metrics, "Add")
	if add.Kind != "function" || add.Receiver != "" {
		t.Fatalf("Add kind/receiver = %q/%q", add.Kind, add.Receiver)
	}
	if add.ParameterCount != 2 || add.ResultCount != 1 {
		t.Fatalf("Add counts = params %d, results %d", add.ParameterCount, add.ResultCount)
	}

	save := metricNamed(t, report.Metrics, "Save")
	if save.Kind != "method" || save.Receiver != "*Store" {
		t.Fatalf("Save kind/receiver = %q/%q", save.Kind, save.Receiver)
	}
	if save.ParameterCount != 4 || save.ResultCount != 2 {
		t.Fatalf("Save counts = params %d, results %d", save.ParameterCount, save.ResultCount)
	}
	if save.CyclomaticComplexity != 3 {
		t.Fatalf("Save complexity = %d, want 3", save.CyclomaticComplexity)
	}
	if save.LineCount != save.EndLine-save.StartLine+1 {
		t.Fatalf("line count %d does not match %d..%d", save.LineCount, save.StartLine, save.EndLine)
	}
}

// TestRunCountsBranches verifies cyclomatic complexity across Go control-flow constructs.
//
// Expected: boolean branches, loops and switch cases contribute to the declared complexity.
func TestRunCountsBranches(t *testing.T) {
	// Given: a function containing boolean, loop and switch branches.
	root := t.TempDir()
	writeGoFixture(t, root, "branch.go",
		"package sample\n\n"+
			"func Branch(value int) int {\n"+
			"\tif value > 0 && value < 10 {\n"+
			"\t\treturn 1\n"+
			"\t}\n"+
			"\tfor value > 0 {\n"+
			"\t\tvalue--\n"+
			"\t}\n"+
			"\tswitch value {\n"+
			"\tcase 1:\n"+
			"\t\treturn 2\n"+
			"\tcase 2:\n"+
			"\t\treturn 3\n"+
			"\tdefault:\n"+
			"\t\treturn 0\n"+
			"\t}\n"+
			"}\n")

	// When: the source metrics are analyzed.
	report, code, stderr := runJSON(t, root)

	// Then: every supported branch contributes to cyclomatic complexity.
	if code != 0 {
		t.Fatalf("run() code = %d, want 0; stderr=%s", code, stderr)
	}
	metric := metricNamed(t, report.Metrics, "Branch")
	if metric.CyclomaticComplexity != 6 {
		t.Fatalf("complexity = %d, want 6", metric.CyclomaticComplexity)
	}
}

// TestRunExcludesGeneratedAndTestFilesByDefault verifies the analyzer's default source boundary.
//
// Expected: generated and test files are excluded unless tests are explicitly requested.
func TestRunExcludesGeneratedAndTestFilesByDefault(t *testing.T) {
	// Given: generated, production and test source files in one package.
	root := t.TempDir()
	writeGoFixture(t, root, "generated.go",
		"// Code generated by fixture. DO NOT EDIT.\n"+
			"package sample\n"+
			"func Generated() {}\n")
	writeGoFixture(t, root, "visible.go", "package sample\nfunc Visible() {}\n")
	writeGoFixture(t, root, "visible_test.go", "package sample\nfunc TestHelper() {}\n")

	// When: metrics are requested with default source boundaries.
	report, code, stderr := runJSON(t, root)

	// Then: only owned production source is reported by default.
	if code != 0 {
		t.Fatalf("run() code = %d, want 0; stderr=%s", code, stderr)
	}
	if len(report.Metrics) != 1 || report.Metrics[0].Name != "Visible" {
		t.Fatalf("default metrics = %#v", report.Metrics)
	}

	// Given: the same source set with test inclusion explicitly requested.
	var stdout bytes.Buffer
	var errout bytes.Buffer
	// When: metrics are requested with test inclusion enabled.
	code = run([]string{"-root", root, "-format", "json", "-include-tests"}, &stdout, &errout)

	// Then: the owned test source joins the report while generated code remains excluded.
	if code != 0 {
		t.Fatalf("include tests code = %d; stderr=%s", code, errout.String())
	}
	if err := json.Unmarshal(stdout.Bytes(), &report); err != nil {
		t.Fatalf("decode include-tests JSON: %v", err)
	}
	if len(report.Metrics) != 2 {
		t.Fatalf("include-tests metrics = %d, want 2", len(report.Metrics))
	}
}

// TestRunRejectsInvalidSyntax verifies parse failures are exposed as operational errors.
//
// Expected: invalid Go returns exit code one with a parse diagnostic.
func TestRunRejectsInvalidSyntax(t *testing.T) {
	// Given: a Go file with invalid syntax.
	root := t.TempDir()
	writeGoFixture(t, root, "invalid.go", "package sample\nfunc Broken( {\n")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	// When: the analyzer attempts to scan the repository.
	code := run([]string{"-root", root}, &stdout, &stderr)

	// Then: it returns an operational failure with a parse diagnostic.
	if code != 1 {
		t.Fatalf("run() code = %d, want 1", code)
	}
	if !strings.Contains(stderr.String(), "parse") {
		t.Fatalf("stderr = %q, want parse diagnostic", stderr.String())
	}
}

// TestRunReturnsTwoWhenConfiguredLimitsAreExceeded verifies policy-limit signaling.
//
// Expected: exceeded line and parameter limits return code two and both violations.
func TestRunReturnsTwoWhenConfiguredLimitsAreExceeded(t *testing.T) {
	// Given: a function exceeding configured line and parameter limits.
	root := t.TempDir()
	writeGoFixture(t, root, "limits.go",
		"package sample\n\n"+
			"func TooMany(first, second int) int {\n"+
			"\tif first > second {\n"+
			"\t\treturn first\n"+
			"\t}\n"+
			"\treturn second\n"+
			"}\n")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	// When: the analyzer applies both policy limits.
	code := run([]string{
		"-root", root,
		"-format", "json",
		"-max-lines", "3",
		"-max-params", "1",
	}, &stdout, &stderr)
	// Then: policy failure code two includes both violations.
	if code != 2 {
		t.Fatalf("run() code = %d, want 2; stderr=%s", code, stderr.String())
	}

	var report Report
	if err := json.Unmarshal(stdout.Bytes(), &report); err != nil {
		t.Fatalf("decode JSON: %v", err)
	}
	if len(report.Violations) != 2 {
		t.Fatalf("violations = %d, want 2: %#v", len(report.Violations), report.Violations)
	}
}

// TestRunWritesStableText verifies the analyzer's human-readable output contract.
//
// Expected: text output includes stable metric headings and the analyzed symbol.
func TestRunWritesStableText(t *testing.T) {
	// Given: one visible function and text output configuration.
	root := t.TempDir()
	writeGoFixture(t, root, "text.go", "package sample\nfunc Visible(value int) int { return value }\n")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	// When: the analyzer renders its human-readable report.
	code := run([]string{"-root", root, "-format", "text"}, &stdout, &stderr)

	// Then: stable headings and the analyzed symbol are present.
	if code != 0 {
		t.Fatalf("run() code = %d; stderr=%s", code, stderr.String())
	}
	for _, want := range []string{"FILE", "NAME", "LINES", "PARAMS", "COMPLEXITY", "Visible"} {
		if !strings.Contains(stdout.String(), want) {
			t.Fatalf("text output missing %q:\n%s", want, stdout.String())
		}
	}
}

// TestScanGoFilesSkipsExcludedDirectories verifies repository traversal exclusions.
//
// Expected: vendor, testdata and Git metadata are ignored while owned source remains.
func TestScanGoFilesSkipsExcludedDirectories(t *testing.T) {
	// Given: owned source plus files under excluded repository directories.
	root := t.TempDir()
	writeGoFixture(t, root, "kept.go", "package sample\nfunc Kept() {}\n")
	writeGoFixture(t, root, filepath.Join("vendor", "ignored.go"), "package vendor\nfunc Ignored() {}\n")
	writeGoFixture(t, root, filepath.Join("testdata", "ignored.go"), "package testdata\nfunc Ignored() {}\n")
	writeGoFixture(t, root, filepath.Join(".git", "ignored.go"), "package git\nfunc Ignored() {}\n")

	// When: repository-owned Go files are discovered.
	files, err := scanGoFiles(root, false)

	// Then: only the owned source remains in the result.
	if err != nil {
		t.Fatalf("scanGoFiles: %v", err)
	}
	if len(files) != 1 || filepath.Base(files[0]) != "kept.go" {
		t.Fatalf("files = %#v", files)
	}
}

func runJSON(t *testing.T, root string) (Report, int, string) {
	t.Helper()
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := run([]string{"-root", root, "-format", "json"}, &stdout, &stderr)
	var report Report
	if stdout.Len() > 0 {
		if err := json.Unmarshal(stdout.Bytes(), &report); err != nil {
			t.Fatalf("decode JSON: %v\n%s", err, stdout.String())
		}
	}
	return report, code, stderr.String()
}

func metricNamed(t *testing.T, metrics []Metric, name string) Metric {
	t.Helper()
	for _, metric := range metrics {
		if metric.Name == name {
			return metric
		}
	}
	t.Fatalf("metric %q not found in %#v", name, metrics)
	return Metric{}
}

func writeGoFixture(t *testing.T, root, relative, content string) {
	t.Helper()
	path := filepath.Join(root, relative)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir fixture: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
}
